CREATE TABLE IF NOT EXISTS admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin')),
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_access TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS admins_email_idx ON admins (email);
CREATE INDEX IF NOT EXISTS admins_status_idx ON admins (status);

CREATE TABLE IF NOT EXISTS city_halls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cidade TEXT NOT NULL,
  estado CHAR(2) NOT NULL,
  cnpj TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('ativo', 'inativo', 'pendente')),
  primary_color TEXT NOT NULL DEFAULT '#0f766e',
  system_name TEXT NOT NULL,
  contact_email TEXT NOT NULL,
  schools INTEGER NOT NULL DEFAULT 0 CHECK (schools >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_access TIMESTAMPTZ,
  modules TEXT[] NOT NULL DEFAULT ARRAY['prefeitura', 'escola', 'responsavel', 'mapa']::TEXT[],
  CONSTRAINT city_halls_modules_check CHECK (modules <@ ARRAY['prefeitura', 'escola', 'responsavel', 'mapa']::TEXT[])
);

CREATE INDEX IF NOT EXISTS city_halls_cnpj_idx ON city_halls (cnpj);
CREATE INDEX IF NOT EXISTS city_halls_email_idx ON city_halls (email);
CREATE INDEX IF NOT EXISTS city_halls_status_idx ON city_halls (status);

CREATE TABLE IF NOT EXISTS settings (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  support_email TEXT NOT NULL,
  system_version TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO settings (id, support_email, system_version)
VALUES (1, 'suporte@sive.com.br', '1.0.0 · Julho 2026')
ON CONFLICT (id) DO NOTHING;