-- Escolas, vinculadas a uma prefeitura
CREATE TABLE IF NOT EXISTS schools (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_hall_id INTEGER NOT NULL REFERENCES city_halls (id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  inep_code TEXT UNIQUE,
  endereco TEXT NOT NULL,
  bairro TEXT,
  cidade TEXT NOT NULL,
  estado CHAR(2) NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS schools_city_hall_id_idx ON schools (city_hall_id);
CREATE INDEX IF NOT EXISTS schools_status_idx ON schools (status);
CREATE INDEX IF NOT EXISTS schools_location_idx ON schools (latitude, longitude);

-- Turmas de uma escola: cada linha representa uma combinacao serie/turno/ano letivo
-- e concentra a capacidade de atendimento usada para calcular vagas disponiveis
CREATE TABLE IF NOT EXISTS school_classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES schools (id) ON DELETE CASCADE,
  serie TEXT NOT NULL,
  turno TEXT NOT NULL CHECK (turno IN ('manha', 'tarde', 'integral', 'noite')),
  ano_letivo SMALLINT NOT NULL,
  capacidade INTEGER NOT NULL CHECK (capacidade >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (school_id, serie, turno, ano_letivo)
);

CREATE INDEX IF NOT EXISTS school_classes_school_id_idx ON school_classes (school_id);
CREATE INDEX IF NOT EXISTS school_classes_ano_letivo_idx ON school_classes (ano_letivo);

-- Alunos
CREATE TABLE IF NOT EXISTS students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cpf TEXT UNIQUE,
  data_nascimento DATE NOT NULL,
  email TEXT UNIQUE,
  password_hash TEXT,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_access TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS students_cpf_idx ON students (cpf);
CREATE INDEX IF NOT EXISTS students_status_idx ON students (status);

-- Responsaveis
CREATE TABLE IF NOT EXISTS guardians (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cpf TEXT UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  telefone TEXT,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_access TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS guardians_email_idx ON guardians (email);
CREATE INDEX IF NOT EXISTS guardians_status_idx ON guardians (status);

-- Vinculo entre alunos e responsaveis (um aluno pode ter mais de um responsavel)
CREATE TABLE IF NOT EXISTS student_guardians (
  student_id INTEGER NOT NULL REFERENCES students (id) ON DELETE CASCADE,
  guardian_id INTEGER NOT NULL REFERENCES guardians (id) ON DELETE CASCADE,
  parentesco TEXT NOT NULL CHECK (parentesco IN ('mae', 'pai', 'responsavel_legal', 'outro')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (student_id, guardian_id)
);

CREATE INDEX IF NOT EXISTS student_guardians_guardian_id_idx ON student_guardians (guardian_id);

-- Matriculas: vincula um aluno a uma turma, com status controlando o ciclo de vida
CREATE TABLE IF NOT EXISTS enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students (id) ON DELETE CASCADE,
  school_class_id INTEGER NOT NULL REFERENCES school_classes (id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'ativa' CHECK (status IN ('ativa', 'cancelada', 'transferida', 'desligada')),
  data_matricula DATE NOT NULL DEFAULT CURRENT_DATE,
  data_saida DATE,
  motivo_saida TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS enrollments_student_id_idx ON enrollments (student_id);
CREATE INDEX IF NOT EXISTS enrollments_school_class_id_idx ON enrollments (school_class_id);
CREATE INDEX IF NOT EXISTS enrollments_status_idx ON enrollments (status);

-- Garante no maximo uma matricula ativa por aluno
CREATE UNIQUE INDEX IF NOT EXISTS enrollments_active_student_idx
  ON enrollments (student_id)
  WHERE status = 'ativa';

-- View auxiliar para o mapa de vagas e o painel da prefeitura:
-- calcula vagas ocupadas/disponiveis por turma a partir das matriculas ativas
CREATE OR REPLACE VIEW school_class_vacancies AS
SELECT
  sc.id AS school_class_id,
  sc.school_id,
  sc.serie,
  sc.turno,
  sc.ano_letivo,
  sc.capacidade,
  COUNT(e.id) FILTER (WHERE e.status = 'ativa') AS vagas_ocupadas,
  sc.capacidade - COUNT(e.id) FILTER (WHERE e.status = 'ativa') AS vagas_disponiveis
FROM school_classes sc
LEFT JOIN enrollments e ON e.school_class_id = sc.id
GROUP BY sc.id, sc.school_id, sc.serie, sc.turno, sc.ano_letivo, sc.capacidade;

-- Log dos eventos recebidos pelos webhooks que atualizam o numero de vagas.
-- external_id garante idempotencia: o mesmo evento, reenviado, nao e processado duas vezes.
CREATE TABLE IF NOT EXISTS enrollment_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'matricula_realizada',
    'cancelamento_matricula',
    'desligamento_aluno',
    'transferencia_escola',
    'alteracao_capacidade'
  )),
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'processado', 'erro')),
  error_message TEXT,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS enrollment_events_event_type_idx ON enrollment_events (event_type);
CREATE INDEX IF NOT EXISTS enrollment_events_status_idx ON enrollment_events (status);